name: Scheduled Publication

on:
  schedule:
    # 毎時0分に実行（1時間ごと）
    - cron: '0 * * * *'
  # 手動実行も可能
  workflow_dispatch: {}

concurrency:
  group: scheduled-publication
  cancel-in-progress: false

jobs:
  trigger-publication:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Call scheduled publication API
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
        run: |
          if [ -z "$APP_URL" ] || [ -z "$CRON_SECRET_TOKEN" ]; then
            echo "APP_URL or CRON_SECRET_TOKEN is not set in repository Secrets" >&2
            exit 1
          fi
          echo "Triggering scheduled publication at $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          curl -sS -X POST "$APP_URL/api/admin/crowdfunding/process-scheduled" \
            -H "Authorization: Bearer $CRON_SECRET_TOKEN" \
            -H "Content-Type: application/json" \
            --retry 3 --retry-delay 5 --fail | jq -r '.' || {
              echo 'Request failed' >&2
              exit 1
            }

