name: Supabase使用量監視

on:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行（UTC時間）
  workflow_dispatch:  # 手動実行用
  push:
    branches:
      - main

jobs:
  monitor-supabase-usage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # 本番環境（mainブランチ）のみ監視
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save @supabase/supabase-js node-fetch
      
      - name: Run monitoring script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: "production"
        run: node scripts/monitoring/supabase-usage.js
      
      - name: Output status on error
        if: failure()
        run: |
          echo "Supabase監視スクリプトの実行中にエラーが発生しました。"
          echo "環境: production"
          echo "GitHub ActionsのSecretsに以下の値が設定されていることを確認してください："
          echo "- SUPABASE_URL"
          echo "- SUPABASE_SERVICE_KEY"
          echo "- SLACK_WEBHOOK_URL（オプション）" 