name: YouTube API使用量監視

on:
  schedule:
    - cron: '0 */4 * * *'  # 4時間ごとに実行（UTC時間）
  workflow_dispatch:  # 手動実行用
  push:
    branches:
      - main

jobs:
  monitor-youtube-api:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch code
        uses: actions/checkout@v3
        with:
          ref: refs/heads/main  # より明示的にmainブランチを指定（デフォルトブランチに関わらず）
          fetch-depth: 1
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save node-fetch
      
      - name: Run monitoring script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: "production"
        run: node scripts/monitoring/youtube-api-usage.js
      
      - name: Output status on error
        if: failure()
        run: |
          echo "YouTube API監視スクリプトの実行中にエラーが発生しました。"
          echo "環境: production"
          echo "GitHub ActionsのSecretsに以下の値が設定されていることを確認してください："
          echo "- YOUTUBE_API_KEY"
          echo "- SLACK_WEBHOOK_URL（オプション）" 